/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.cliente;

import pacote.relatorio.RPCliente;
import pacote.relatorio.RPEquipamento;
import pacote.relatorio.RPFuncionario;
import pacote.relatorio.RPTreino;
import visao.treino.AtualizarTreino;
import visao.treino.DeletarTreino;
import visao.equipamento.CadastroEquipamento;
import visao.treino.CadastroTreino;
import visao.treino.CadastroTreino;
import visao.treino.VisualizarTreino;
import visao.funcionario.AtualizarFuncionario;
import visao.funcionario.CadastroFuncionario;
import visao.funcionario.DeletarFuncionario;
import visao.funcionario.VisualizarFuncionario;
import visao.cliente.AtualizarCliente;
import visao.cliente.CadastroCliente;
import visao.cliente.DeletarCliente;
import visao.cliente.VisualizarCliente;
import visao.equipamento.AtualizarEquipamento;
import visao.equipamento.DeletarEquipamento;
import visao.equipamento.VisualizarEquipamento;

/**
 *
 * @author Alexandre Rocha
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        itemMenuCliente = new javax.swing.JMenuItem();
        itemMenuVisualizarCliente = new javax.swing.JMenuItem();
        itemMenuAtualizarCliente = new javax.swing.JMenuItem();
        itemMenuDeletarCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemMenuCadastroFuncionario = new javax.swing.JMenuItem();
        itemMenuVisualizarFuncionario = new javax.swing.JMenuItem();
        itemMenuAtualizarFuncionario = new javax.swing.JMenuItem();
        itemMenuDeletarFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMenuCadastroEquipamento = new javax.swing.JMenuItem();
        itemMenuVisualizarEquipamento = new javax.swing.JMenuItem();
        itemMenuAtualizarEquipamento = new javax.swing.JMenuItem();
        itemMenuDeletarEquipamento = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        itemMenuCadastroTreino = new javax.swing.JMenuItem();
        itemMenuVisualizarTreino = new javax.swing.JMenuItem();
        itemMenuAtualizarTreino = new javax.swing.JMenuItem();
        itemMenuDeletarTreino = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemMenuRelatorioCliente = new javax.swing.JMenuItem();
        itemMenuRelatorioFuncionario = new javax.swing.JMenuItem();
        itemMenuRelatorioEquipamento = new javax.swing.JMenuItem();
        itemMenuRelatorioTreino = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenu();
        itemMenuSairSistema = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Academia");

        jPanel1.setBackground(new java.awt.Color(216, 216, 242));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Logo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Slogan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));

        menuCliente.setText("Cliente");

        itemMenuCliente.setText("Cadastrar Cliente");
        itemMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuCliente);

        itemMenuVisualizarCliente.setText("Visualizar");
        itemMenuVisualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuVisualizarCliente);

        itemMenuAtualizarCliente.setText("Atualizar");
        itemMenuAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuAtualizarCliente);

        itemMenuDeletarCliente.setText("Deletar");
        itemMenuDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(itemMenuDeletarCliente);

        jMenuBar1.add(menuCliente);

        jMenu1.setText("Funcionário");

        itemMenuCadastroFuncionario.setText("Cadastrar Funcionário");
        itemMenuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuCadastroFuncionario);

        itemMenuVisualizarFuncionario.setText("Visualizar");
        itemMenuVisualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuVisualizarFuncionario);

        itemMenuAtualizarFuncionario.setText("Atualizar");
        itemMenuAtualizarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuAtualizarFuncionario);

        itemMenuDeletarFuncionario.setText("Deletar");
        itemMenuDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuDeletarFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Equipamento");

        itemMenuCadastroEquipamento.setText("Cadastrar Equipamento");
        itemMenuCadastroEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroEquipamentoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuCadastroEquipamento);

        itemMenuVisualizarEquipamento.setText("Visualizar");
        itemMenuVisualizarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarEquipamentoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuVisualizarEquipamento);

        itemMenuAtualizarEquipamento.setText("Atualizar");
        itemMenuAtualizarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarEquipamentoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuAtualizarEquipamento);

        itemMenuDeletarEquipamento.setText("Deletar");
        itemMenuDeletarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarEquipamentoActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuDeletarEquipamento);

        jMenuBar1.add(jMenu2);

        menuAgendamento.setText("Treino");

        itemMenuCadastroTreino.setText("Cadastrar Treino");
        itemMenuCadastroTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCadastroTreinoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuCadastroTreino);

        itemMenuVisualizarTreino.setText("Visualizar");
        itemMenuVisualizarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVisualizarTreinoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuVisualizarTreino);

        itemMenuAtualizarTreino.setText("Atualizar");
        itemMenuAtualizarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAtualizarTreinoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAtualizarTreino);

        itemMenuDeletarTreino.setText("Deletar");
        itemMenuDeletarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDeletarTreinoActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuDeletarTreino);

        jMenuBar1.add(menuAgendamento);

        jMenu3.setText("Relatorios");

        itemMenuRelatorioCliente.setText("Cliente");
        itemMenuRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioClienteActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuRelatorioCliente);

        itemMenuRelatorioFuncionario.setText("Funcionário");
        itemMenuRelatorioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioFuncionarioActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuRelatorioFuncionario);

        itemMenuRelatorioEquipamento.setText("Equipamento");
        itemMenuRelatorioEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioEquipamentoActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuRelatorioEquipamento);

        itemMenuRelatorioTreino.setText("Treino");
        itemMenuRelatorioTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioTreinoActionPerformed(evt);
            }
        });
        jMenu3.add(itemMenuRelatorioTreino);

        jMenuBar1.add(jMenu3);

        itemMenuSair.setText("Sair");

        itemMenuSairSistema.setText("Sair do Sistema");
        itemMenuSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairSistemaActionPerformed(evt);
            }
        });
        itemMenuSair.add(itemMenuSairSistema);

        jMenuBar1.add(itemMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroFuncionarioActionPerformed

    private void itemMenuCadastroEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroEquipamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroEquipamento().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroEquipamentoActionPerformed

    private void itemMenuCadastroTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCadastroTreinoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroTreino().setVisible(true);
    }//GEN-LAST:event_itemMenuCadastroTreinoActionPerformed

    private void itemMenuVisualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarClienteActionPerformed

    private void itemMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CadastroCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuClienteActionPerformed

    private void itemMenuAtualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarFuncionario().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarFuncionarioActionPerformed

    private void itemMenuAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarClienteActionPerformed

    private void itemMenuSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairSistemaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemMenuSairSistemaActionPerformed

    private void itemMenuDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarClienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarCliente().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarClienteActionPerformed

    private void itemMenuVisualizarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarFuncionario().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarFuncionarioActionPerformed

    private void itemMenuDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarFuncionarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarFuncionario().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarFuncionarioActionPerformed

    private void itemMenuVisualizarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarTreinoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarTreino().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarTreinoActionPerformed

    private void itemMenuAtualizarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarTreinoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarTreino().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarTreinoActionPerformed

    private void itemMenuDeletarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarTreinoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarTreino().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarTreinoActionPerformed

    private void itemMenuVisualizarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVisualizarEquipamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new VisualizarEquipamento().setVisible(true);
    }//GEN-LAST:event_itemMenuVisualizarEquipamentoActionPerformed

    private void itemMenuAtualizarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAtualizarEquipamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AtualizarEquipamento().setVisible(true);
    }//GEN-LAST:event_itemMenuAtualizarEquipamentoActionPerformed

    private void itemMenuDeletarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDeletarEquipamentoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeletarEquipamento().setVisible(true);
    }//GEN-LAST:event_itemMenuDeletarEquipamentoActionPerformed

    private void itemMenuRelatorioEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioEquipamentoActionPerformed
        // TODO add your handling code here:
        RPEquipamento relatorioEquipamento = new RPEquipamento();
        relatorioEquipamento.gerarRelatorioTotal
        //("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
        //("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioEquipamento.jasper");
        ("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova 3 (pronto)\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioEquipamento.jasper");
    }//GEN-LAST:event_itemMenuRelatorioEquipamentoActionPerformed

    private void itemMenuRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioClienteActionPerformed
        // TODO add your handling code here:
        RPCliente relatorioCliente = new RPCliente();
        relatorioCliente.gerarRelatorioTotal
        //("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
        //("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioCliente.jasper");
        ("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova 3 (pronto)\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioCliente.jasper");
    }//GEN-LAST:event_itemMenuRelatorioClienteActionPerformed

    private void itemMenuRelatorioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioFuncionarioActionPerformed
        // TODO add your handling code here:
        RPFuncionario relatorioFuncionario = new RPFuncionario();
        relatorioFuncionario.gerarRelatorioTotal
        //("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
        //("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioFuncionario.jasper");
        ("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova 3 (pronto)\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioFuncionario.jasper");
    }//GEN-LAST:event_itemMenuRelatorioFuncionarioActionPerformed

    private void itemMenuRelatorioTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioTreinoActionPerformed
        // TODO add your handling code here:
        RPTreino relatorioTreino = new RPTreino();
        relatorioTreino.gerarRelatorioTotal
        // ("E:\\Dados Ligia\\IFTM-Professora\\Disciplinas\\Programação Orientada Eventos\\Aulas\\Códigos\\17_Aula_CRUD_Relatórios\\src\\pacote\\relatorio\\RelatorioGeral.jasper");
        // ("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioTreino.jasper");
        ("D:\\FACULDADE\\4° - Periodo\\POE\\Prova - 3\\Prova 3 (pronto)\\Prova3-Academia\\Prova3-AlexandreERaquel\\src\\pacote\\relatorio\\RelatorioTreino.jasper");
    }//GEN-LAST:event_itemMenuRelatorioTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuAtualizarCliente;
    private javax.swing.JMenuItem itemMenuAtualizarEquipamento;
    private javax.swing.JMenuItem itemMenuAtualizarFuncionario;
    private javax.swing.JMenuItem itemMenuAtualizarTreino;
    private javax.swing.JMenuItem itemMenuCadastroEquipamento;
    private javax.swing.JMenuItem itemMenuCadastroFuncionario;
    private javax.swing.JMenuItem itemMenuCadastroTreino;
    private javax.swing.JMenuItem itemMenuCliente;
    private javax.swing.JMenuItem itemMenuDeletarCliente;
    private javax.swing.JMenuItem itemMenuDeletarEquipamento;
    private javax.swing.JMenuItem itemMenuDeletarFuncionario;
    private javax.swing.JMenuItem itemMenuDeletarTreino;
    private javax.swing.JMenuItem itemMenuRelatorioCliente;
    private javax.swing.JMenuItem itemMenuRelatorioEquipamento;
    private javax.swing.JMenuItem itemMenuRelatorioFuncionario;
    private javax.swing.JMenuItem itemMenuRelatorioTreino;
    private javax.swing.JMenu itemMenuSair;
    private javax.swing.JMenuItem itemMenuSairSistema;
    private javax.swing.JMenuItem itemMenuVisualizarCliente;
    private javax.swing.JMenuItem itemMenuVisualizarEquipamento;
    private javax.swing.JMenuItem itemMenuVisualizarFuncionario;
    private javax.swing.JMenuItem itemMenuVisualizarTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuCliente;
    // End of variables declaration//GEN-END:variables
}
